repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^frontend/src/api/|^frontend/src/schemas/|^backend/app/schemas/
      - id: end-of-file-fixer
        exclude: ^frontend/src/api/|^frontend/src/schemas/|^backend/app/schemas/
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
        exclude: ^frontend/src/api/|^frontend/src/schemas/|^backend/app/schemas/
      - id: check-toml
      - id: debug-statements
