# Import generated schemas from centralized JSON Schema definitions
from .schemas.v1.api.requests import (
    AssignColorRequest,
    CreateTeamRequest,
    GameSessionCreate,
    GameSessionStateUpdate,
    GetCurrentPuzzleRequest,
    GetGameResultRequest,
    GetGameStateRequest,
    JoinTeamRequest,
    PuzzleAnswer,
    PuzzleCreate,
    RestartGameRequest,
    StartGameRequest,
    SubmitAnswerRequest,
    TeamCreate,
    UpdatePlayerReadyRequest,
    UserCreate,
)
from .schemas.v1.api.responses import (
    ApiResponse,
    AvailableColorsResponse,
    AvailableTeamOut,
    ColorAssignmentResponse,
    ColorConflictResolutionResponse,
    ErrorResponse,
    GameSessionOut,
    HealthCheckResponse,
    PlayerPoints,
    PuzzleResult,
    PuzzleState,
    SuccessResponse,
    TeamColorValidationResponse,
    TeamOut,
    TeamPoints,
    TeamWithMembersOut,
    UserOut,
)


# Re-export all schemas for backward compatibility
__all__ = [
    # Request schemas
    "UserCreate",
    "TeamCreate",
    "GameSessionCreate",
    "GameSessionStateUpdate",
    "PuzzleCreate",
    "PuzzleAnswer",
    "AssignColorRequest",
    "UpdatePlayerReadyRequest",
    "GetGameStateRequest",
    "GetGameResultRequest",
    "RestartGameRequest",
    "GetCurrentPuzzleRequest",
    "SubmitAnswerRequest",
    "StartGameRequest",
    "CreateTeamRequest",
    "JoinTeamRequest",
    # Response schemas
    "UserOut",
    "TeamOut",
    "TeamWithMembersOut",
    "AvailableTeamOut",
    "GameSessionOut",
    "PuzzleState",
    "PuzzleResult",
    "PlayerPoints",
    "TeamPoints",
    "ColorAssignmentResponse",
    "ColorConflictResolutionResponse",
    "TeamColorValidationResponse",
    "AvailableColorsResponse",
    "ApiResponse",
    "ErrorResponse",
    "SuccessResponse",
    "HealthCheckResponse",
]
