name: CI

on:
  pull_request:
    branches: [ main, master ]
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Set up Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'

    - name: Install Python dependencies
      run: |
        cd backend
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Install Node.js dependencies
      run: |
        cd frontend
        npm ci

    - name: Generate schemas
      run: |
        cd backend
        source venv/bin/activate
        python ../schemas/generator/generate_python.py --schemas-dir ../schemas --output-dir app/schemas
        python ../schemas/generator/generate_typescript.py --schemas-dir ../schemas --output-dir ../frontend/src/schemas

    - name: Run backend code formatting
      run: |
        cd backend
        source venv/bin/activate
        ruff format app/ ../schemas/ --exclude app/schemas/

    - name: Run backend linting
      run: |
        cd backend
        source venv/bin/activate
        ruff check app/ ../schemas/ --fix --exclude app/schemas/

    - name: Run backend type checking
      run: |
        cd backend
        source venv/bin/activate
        mypy --explicit-package-bases . ../schemas/

    - name: Run backend tests
      run: |
        make test-backend

    - name: Run frontend linting
      run: |
        cd frontend
        npm run lint

    - name: Run frontend tests
      run: |
        cd frontend
        npm test

    - name: Run frontend type checking
      run: |
        cd frontend
        npm run build
